### PR TITLE
Priors for causal types

### PR DESCRIPTION
**Pull request by lilymedina**
Opening PR to keep track of WIP

`make_priors` seems to be working ok for both confounded and nonconfounded models. See usage below.

 
```
# A nonconfounded model
XYmodel <- make_model("X -> Y")

# specify priors using query syntax
 make_priors(model   = XYmodel, 
              alphas = c(`(Y[X=1] == Y[X=0])`  = 3,  `X == 1` = 3  ))
 > X.X0  X.X1 Y.Y00 Y.Y10 Y.Y01 Y.Y11 
      1     3     3     1     1     3 
```

Or using both parameter and query syntax

```
 make_priors(model  = XYmodel,
            alphas  = list(X = c(X0 = 2, `X == 1` = 3), 
                           Y = c(`(Y[X=1] > Y[X=0])` = 3, 
                           Y10 = 2, 
                          `(Y[X=1] == Y[X=0])`  = 3)))
> X.X0  X.X1 Y.Y00 Y.Y10 Y.Y01 Y.Y11 
     2     3     3     2     3     3 

````

Accepts duplicates in priors as long as there are no discrepancies
``` 
# This is ok
make_priors(model = XYmodel,  alphas = list(X = c(X0 = 2, `X == 0` = 2)))
> X.X0  X.X1 Y.Y00 Y.Y10 Y.Y01 Y.Y11 
     2     1     1     1     1     1 

# The following should produce an error 
#  and it does but error message has currently some bug 
make_priors(model = XYmodel,
            alphas = list(X = c(X0 = 2, `X == 0` = 3)))
> Error in make_alphas(model, alphas) : 
  Please solve the following discrepancies 
```

it also works for confounded models though I'd like to test this feature a bit more

```
model <-make_model("X -> Y")%>%
	set_confound(list(X = "(Y[X=1]>Y[X=0])"))

make_priors(model = model,  alphas =  c(`X == 0` = 2))
> X.1.X0.1 X.1.X1.1     X.X0     X.X1    Y.Y00    Y.Y10    Y.Y01    Y.Y11 
        2        1        2        1        1        1        1        1 
```

It can also target the variable modeling the confound by adding a condition to query.
```
make_priors(model = model,  alphas =  c(`(X == 0) & (Y[X=1]>Y[X=0])` = 2))
> X.1.X0.1 X.1.X1.1     X.X0     X.X1    Y.Y00    Y.Y10    Y.Y01    Y.Y11 
        2        1        1        1        1        1        1        1 
```
logical complement sets prior of X.X0 to 2
```
make_priors(model = model,  alphas =  c(`(X == 0) & (Y[X=1]<=Y[X=0])` = 2))
> X.1.X0.1 X.1.X1.1     X.X0     X.X1    Y.Y00    Y.Y10    Y.Y01    Y.Y11 
        1        1        2        1        1        1        1        1 

```

Thoughts and review are welcome!

### CODE REVIEW

**Comment by lilymedina** [comment]
This PR also creates a set of functions used to set priors that can potentially come in handy for other features.

Worth mentioning are 
- `types_to_nodes` identifies nodes that satisfy a causal type query.
```
XYmodel <- make_model("X -> Y")
gbiqq:::types_to_nodes(XYmodel, "X==0")
> $X
> [1] "X0"
```
- `types_to_rows` identifies rows in the parameter matrix that satisfy a causal type query. If model has no confounds then `types_to_rows` simply calls `types_to_nodes`

**Comment by lilymedina** [comment]
To do

- [ ]  tests
- [ ]  more and better examples and in general better documentation
- [ ]  code cleaning for clarity
- [ ]  better and exhaustive error messages

**Comment by lilymedina** [comment]
This PR would solve issues [#19](https://github.com/macartan/gbiqq/issues/19l) [#47] and (https://github.com/macartan/gbiqq/issues/47)

It looks good to me already. Error messages can still be improved a lot but that's an issue for most of the package. 

Feel free to try the function out and share your thoughts!

**Comment by macartan** [comment]
great!

**Pull request merged**
