### PR TITLE
more informative error message in map_query_to_causal_types

### PR DESCRIPTION
**Pull request by lilymedina**
This PR
- adds error messages when expressions do not return causal types
- include tests for error message above
- removes redundant code in 
- corrects function reference in `reveal_outcome`

### CODE REVIEW

**Comment by lilymedina** [comment]
Don't panic. Travis is breaking because R release version in travis hasn't been updated.

**Comment by macartan** [comment]
@juliosolisar did you issue up the ideas of making `get_query_types` by a user facing handler for teh two `map_` functions and then no longer exporting the `map_` functions?

@lilymedina we have `get_query_types` in teh cheatsheet but the function no longer exists. Should be quick job to bring it back however as a handler

**Comment by juliosolisar** [comment]
> @juliosolisar did you issue up the ideas of making `get_query_types` by a user facing handler for teh two `map_` functions and then no longer exporting the `map_` functions?
> 
> @lilymedina we have `get_query_types` in teh cheatsheet but the function no longer exists. Should be quick job to bring it back however as a handler

@macartan @lilymedina this is already done in PR "get_query_types".

**Comment by macartan** [comment]
thanks!!

**Pull request merged**
