### PR TITLE
create covr report

### PR DESCRIPTION
**Pull request by lilymedina**
This PR solves issue #155. At least it does so on mac.

@macartan or @juliosolisar could you check if it works fine on windows?

### CODE REVIEW

**Comment by macartan** [comment]
can you send the report?

I still get:

> x <- covr::package_coverage(quiet = FALSE)Warning: unknown option '--with-keep.parse.data'
Warning: unknown option '--no-staged-install'
* installing *source* package 'gbiqq' ...
** libs
Error in .shlib_internal(args) :
  C++14 standard requested but CXX14 is not defined
* removing 'C:/Users/macar/AppData/Local/Temp/RtmpqWqBQT/R_LIBS3c183f2275b6/gbiqq'
In R CMD INSTALLError in file(con, "r") : cannot open the connectionIn
addition: Warning messages:1: In utils::install.packages(repos = NULL,
lib = tmp_lib, pkg$path,  :  installation of package
‘C:/Dropbox/github/gbiqq’ had non-zero exit status2: In file(con, "r")
:  cannot open file
'C:/Users/macar/AppData/Local/Temp/RtmpqWqBQT/R_LIBS3c183f2275b6/gbiqq/R/gbiqq':
No such file or directory


>

**Comment by lilymedina** [comment]
Have a look [here](https://coveralls.io/builds/28930092)

**Comment by lilymedina** [comment]
Frustrating that it doesn't work on windows. Travis creates report on mac and linux

**Comment by macartan** [comment]
ok thanks

@julio the weak ones are

reveal_outcomes
plot_dag
misc
map_query_to_nodal_type

maybe focus on tests for those?

**Comment by juliosolisar** [comment]
Great, will be working on that TODAY

**Pull request merged**
