### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by MerlinHeidemanns**
Passes with 0 errors ✔ | 2 warnings ✖ | 2 notes ✖;
about 91% coverage

### CODE REVIEW

**Comment by lilymedina** [comment]
This is great! Though still having issues passing checks. Could you please share your session info. @MerlinHeidemanns?

**Comment by MerlinHeidemanns** [comment]
Sure. Sorry for that!

Session info:

R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] gbiqq_0.0.2 dplyr_0.8.3 Rcpp_1.0.2 

loaded via a namespace (and not attached):
 [1] pillar_1.4.2       compiler_3.5.3    
 [3] plyr_1.8.4         prettyunits_1.0.2 
 [5] tools_3.5.3        pkgbuild_1.0.6    
 [7] tibble_2.1.3       gtable_0.2.0      
 [9] pkgconfig_2.0.1    rlang_0.4.0       
[11] cli_1.1.0          rstudioapi_0.8    
[13] parallel_3.5.3     yaml_2.1.18       
[15] loo_2.1.0          gridExtra_2.3     
[17] stringr_1.3.1      gtools_3.5.0      
[19] stats4_3.5.3       grid_3.5.3        
[21] tidyselect_0.2.5   glue_1.3.0        
[23] inline_0.3.14      R6_2.3.0          
[25] processx_3.4.1     rstan_2.19.2      
[27] callr_3.3.2        purrr_0.3.3       
[29] ggplot2_3.0.0      magrittr_1.5      
[31] scales_1.0.0       ps_1.2.1          
[33] StanHeaders_2.19.0 matrixStats_0.54.0
[35] assertthat_0.2.0   colorspace_1.4-1  
[37] stringi_1.2.4      lazyeval_0.2.1    
[39] munsell_0.5.0      crayon_1.3.4

**Comment by MerlinHeidemanns** [comment]
Is anything failing in particular?

**Comment by lilymedina** [comment]
> Is anything failing in particular?

It breaks in the `make_confound_df` examples in the lines where model is plotted.

**Comment by lilymedina** [comment]
Most salient difference is our R versions. Mine is 3.6.2. I'll try with 3.5. 
Thanks!

**Comment by MerlinHeidemanns** [comment]
Yes, that could be the issue. I just tested the examples and they work for me (and were also passed by devtools::check).

**Comment by lilymedina** [comment]
LGTM
checks passing on R-3.5.3 and coverage looking good.

**Pull request merged**
