### PR TITLE
Refunction interpretation of nodal type

### LINKED ISSUE #8: interpretation of nodal types
generate this for construction of P matrix, not with reduction of nodal types

### PR DESCRIPTION
**Pull request by clarabicalho**
- Creates new helpers `type_matrix()` and `clean_condition()`
- Creates `lookup_type()`, which can addresses the two features in #8 (closes #8). 

Specifically, one can ask for interpretation of a given `position` of a nodal type for a given variable:
```
model <- make_model("R -> X; O ->X; Z -> X; X -> Y")
lookup_type(model, position = list(X = c(3,4), Y = 1))
```
or ask for the position in the nodal type of the outcome that indicates a given `condition`.
```
lookup_type(model, condition = c("X | Z=0 & O=1 & R=1", "X | Z=0 & O=1 & R=0"))
```
or demand interpretation and positions for all nodal types
```
lookup_type(model)
```
- Updated `get_nodal_types()` adds the default from `lookup_type(model)` to attribute "interpret".

### CODE REVIEW

**Comment by clarabicalho** [comment]
@macartan @lilymedina thoughts?

**Comment by macartan** [comment]
Looks great.

**Comment by macartan** [comment]
Wondering if these functions Willbe helpful for defining priors/ parameters in a more intuitive way?

**Comment by lilymedina** [comment]
This is really neat!! 

Sorry for slow review.

**Pull request merged**
