### PR TITLE
characters in priors argument

### PR DESCRIPTION
**Pull request by juliosolisar**
error message when trying to pass a character to priors argument (previously changed priors to whatever the character said)

### CODE REVIEW

**Comment by macartan** [comment]
I think you can replace
`(!is.null(priors) & is.character(priors))`
with
`(is.character(priors))`

e.g.
> priors <- NULL
> (is.character(priors))
[1] FALSE

also make it "non negative real numbers"
since 0 is allowed (also, numberS)

**Comment by macartan** [comment]
Though a more general check to see if it is numeric would be:

(!is.null(priors) && !is.numeric(priors))

**Comment by juliosolisar** [comment]
done as last suggested. changed documentation of alphas argument to allow for zero

**Comment by juliosolisar** [comment]
In this branch:

- Minor changes in documentation of arguments

- Argument `priors `in `set_priors `must be real non negative numbers

- New argument `nodal_type` just another way to pass `label `(further enhancement could drop argument `label`

- New argument `param_names`

- New argument `param_set`

- `set_parameters` family modified accordingly

Tests run fine but getting error in checks.

**Pull request merged**
